name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ghlee9883/juntamsae
          stage: main
          yaml: >
            name: juntamsae

            app: node@18

            options:
              env:
                - name: PORT
                  value: "8080"
                - name: DB_URL
                  value: mongodb+srv://juntamsae2023:khucsejuntamsae23@juntamsae.jlnig61.mongodb.net/?retryWrites=true&w=majority
                - name: SECRET_CODE
                  value: gwangholee9883
                - name: CRYPTO_CODE
                  value: "103821"
              ports: "8080"
              install: npm install
              start: node server
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
